spring:
  datasource:
    url: jdbc:postgresql://buttercookie-db.c5m0icyk0ujr.ap-northeast-2.rds.amazonaws.com:5432/postgres
    driverClassName: org.postgresql.Driver
    username: buttercookie
    password: mettredulce

frontend:
  url: https://grocery-self.vercel.app