spring:
  application:
    name: app-server

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/grocery
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: leejay
    password: dltmdwl

  sql:
    init:
      platform: mysql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope:
            - email
            - profile

logging:
  level:
    root: INFO
    com.grocery.app_server: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  servlet:
    session:
      timeout: 30m