spring:
  application:
    name: app-server

  datasource:
    url: jdbc:postgresql://127.0.0.1:5431/postgres
    driverClassName: org.postgresql.Driver
    username: buttercookie
    password: mettredulce

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      platform: postgresql

logging:
  level:
    root: INFO
    com.grocery.app_server: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  servlet:
    session:
      timeout: 30m