spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buttercloud
    username: postgres
    password: postgres1234
    driver-class-name: org.postgresql.Driver

frontend:
  url: http://localhost:3000